spring:
  application:
    name: advertising-tg-bot-service

  config:
    import:
      - optional:classpath:advertising-tg-bot.env.template[.properties]

server:
  port: 8081

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:dummy-token-for-local}